### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by tranceptor** [fwartner/maps#1]
Hi, today I was launching "composer update" on my Laravel 4.2.* installation.
This is the error I received:
[RuntimeException]
  Failed to clone git@github.com:appitventures/Phpgmaps.git via git, https, ssh protocols, aborting.
  - git://github.com/appitventures/Phpgmaps.git
    fatal: remote error:
      Repository not found.
  - https://github.com/appitventures/Phpgmaps.git
    error: Problem with the SSL CA cert (path? access rights?) while accessing https://github.com/appitventures/Phpgmaps.git/info/refs
    fatal: HTTP request failed
  - git@github.com:appitventures/Phpgmaps.git
    ERROR: Repository not found.
    fatal: The remote end hung up unexpectedly

In fact, https://github.com/appitventures/Phpgmaps.git gives me a 404 error. What am I wrong?

**Comment by sdeering** [comment]
The repo for this no longer exists?

https://github.com/appitventures/Phpgmaps

**Comment by fwartner** [comment]
It does. But i made some changes for my own project.

**Comment by fwartner** [comment]
Update: It doesn´t.

**Comment by sdeering** [comment]
One of my projects uses this repo as a dependency, would you allow me to fork it? or whats the plan for people who are using it?

**Comment by fwartner** [comment]
Of course. It´s open source if it´s not private :)

Feel free to make a pr.

**Comment by sdeering** [comment]
Cool thanks, any ideas why this repo doesn't exist anymore? https://github.com/appitventures/Phpgmaps

**Comment by fwartner** [comment]
Nope.. :/

**Comment by sdeering** [comment]
Because your repo has this one as a dependency would it not also break yours?

**Comment by fwartner** [comment]
Until now everything´s working fine for me.
